### ISSUE TITLE
Autotest Tutorials 

### ISSUE THREAD

**Issue by teubert** [nasa/prog_algs#128]
Implement tools so tutorials are automatically tested (e.g., https://papermill.readthedocs.io)

## D.o.D
- [ ] Tutorials are tested as part of each PR.

**Comment by lawrence-hwang** [comment]
`https://www.losant.com/blog/automating-unit-tests-for-jupyter-python-notebooks-using-ipynb-and-nbmake`
`https://semaphoreci.com/blog/test-jupyter-notebooks-with-pytest-and-nbmake`

**Comment by lawrence-hwang** [comment]
[https://stackoverflow.com/questions/40172281/unit-tests-for-functions-in-a-jupyter-notebook](https://stackoverflow.com/questions/40172281/unit-tests-for-functions-in-a-jupyter-notebook)

[testbook](https://pypi.org/project/testbook/)

**Comment by lawrence-hwang** [comment]
For running the notebook tutorial file

[https://mybinder.org/v2/gh/nasa/prog_algs/master/?labpath=tutorial.ipynb](https://mybinder.org/v2/gh/nasa/prog_algs/master/?labpath=tutorial.ipynb)

**Comment by lawrence-hwang** [comment]
Testing tutorial files only for successful execution.

Decided against testing cells individually as tutorial files are highly subject to change with the addition of new features, bug fixes, etcetera. Testing structure is delicate and challenging to change.

**Comment by lawrence-hwang** [comment]
<img width="1138" alt="Screen Shot 2022-03-04 at 10 22 10 AM" src="https://user-images.githubusercontent.com/50124505/156820151-2aaaca1f-20f4-4679-9e0b-108435e34936.png">

<img width="1319" alt="Screen Shot 2022-03-04 at 10 23 04 AM" src="https://user-images.githubusercontent.com/50124505/156820255-dae747e6-90b0-4541-a278-15e887966807.png">

**Comment by lawrence-hwang** [comment]
https://queirozf.com/entries/jupyter-kernels-how-to-add-change-remove
